use std::env;
use std::fs;
use std::path::Path;

use spirv_builder::MetadataPrintout;
use spirv_builder::ModuleResult;
use spirv_builder::SpirvBuilder;
use spirv_builder::SpirvMetadata;
// assuming SpirvBuilder, etc are imported from spirv-builder

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=crates/game_engine_shaders/src");

    // 1. Run the compilation
    let compile_result = SpirvBuilder::new("crates/game_engine_shaders", "spirv-unknown-vulkan1.4")
        .print_metadata(MetadataPrintout::Full)
        .spirv_metadata(SpirvMetadata::NameVariables)
        .build()?;

    // 2. Prepare to generate Rust code
    let mut generated_rs = String::new();

    generated_rs.push_str("// Auto-generated by build.rs\n\n");

    // 3. Helper function to format the module string
    let generate_mod_code = |mod_name: &str, file_path: &Path| -> String {
        // Sanitize path for Windows/Linux compatibility in string literals
        let safe_path = file_path
            .to_str()
            .expect("Path is not valid UTF-8")
            .replace("\\", "/");

        // Sanitize module name (replace :: with _ for rust-gpu namespaces)
        let safe_mod_name = mod_name
            .replace("::", "_")
            .replace("-", "_")
            .replace(".", "_");

        format!(
            r#"
            pub mod {} {{
                vulkano_shaders::shader! {{
                    bytes: "{}"
                }}
            }}
            "#,
            safe_mod_name, safe_path
        )
    };

    // 4. Iterate over results and append code
    match &compile_result.module {
        ModuleResult::SingleModule(path) => {
            // For a single module, default the name to "main" or the file stem
            let name = path.file_stem().unwrap_or_default().to_string_lossy();
            generated_rs.push_str(&generate_mod_code(&name, path));
        }
        ModuleResult::MultiModule(map) => {
            for (name, path) in map {
                generated_rs.push_str(&generate_mod_code(name, path));
            }
        }
    }

    // 5. Write the generated code to OUT_DIR
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("spiv_shaders.rs");

    fs::write(&dest_path, generated_rs)?;

    Ok(())
}
